### ISSUE TITLE
MacOS下浏览器全屏模式搜索会创建多桌面

### ISSUE THREAD

**Issue by SadnAp** [VecHK/poker-search#210]
很怪,有概率复现,时好时坏

**Comment by SadnAp** [comment]
大概确定了,全屏下搜索会创建一个当前桌面A以外的新桌面B并开始Poker,若此时用户因未知原因仍留在桌面A或手动返回,拓展会继续创建新桌面

**Comment by VecHK** [comment]
谢谢指出，已经确认。

**Comment by VecHK** [comment]
@all-contributors please add @SadnAp for bug
