### ISSUE TITLE
Poker 会覆盖百度搜索结果页面的其他元素

### ISSUE THREAD

**Issue by bainesing** [VecHK/poker-search#217]
以百度举例，搜索结果页面会出现插件提供的搜索建议“找不到想要的结果？试试 Poker”，此功能会覆盖百度搜索结果右侧的其他信息。

复现详情请参照下图：

![image](https://user-images.githubusercontent.com/14970892/183231534-f6723e7c-112d-4a8b-a3d0-6c60bed0b846.png)

**Comment by VecHK** [comment]
已经确认，感谢反馈

**Comment by VecHK** [comment]
@all-contributors please add @bainesing for bug
