### ISSUE TITLE
本地的poker页面，可在新建窗口、新建标签页中打开

### ISSUE THREAD

**Issue by nt-cubic** [VecHK/poker-search#39]
现在每次搜索都只能输入个poker实在是繁琐，容易忘记这回事。
要是能一打开浏览器就tm是poker的搜索框就好了

**Comment by VecHK** [comment]
似乎没有必要了，入口也够多。而且要实现一个与原版相同功能的新建标签页也很麻烦，又要多拿“bookmark”的权限
